#!/bin/sh -f

# Quick shell script that moves me repknight creds
repknight

mkdir $1
cd $1
git init

GISTDIR="/tmp/$$"
git clone https://gist.github.com/5669227.git $GISTDIR 
mv $GISTDIR/README.md .
git add README.md 
rm -fr $GISTDIR

git commit -m 'Skeleton Create (from script)'
git remote add origin git@vcs.repknight.com:$1.git
git push -u origin master
