#!/bin/sh -f

mkdir $1
cd $1
git init

GISTDIR="/tmp/$$"
git clone https://gist.github.com/5669227.git $GISTDIR 
mv $GISTDIR/README.md .
git add README.md 
rm -fr $GISTDIR

git commit -m 'Skeleton Create (from script)'
git push -u origin master
